FROM node:22.12.0

WORKDIR /app

# docker build -t test-node .

# docker run --rm -it --name container-1 -v ${PWD}/shared_file/:/app/shared_file test-node sh

# while sleep 3; do echo "$(date '+%Y-%m-%dT%H:%M:%S%z') 123 from file 1" > file.js; done
